global:
  scrape_interval: 15s # Fréquence à laquelle Prometheus va scraper les métriques
  evaluation_interval: 15s # Fréquence à laquelle les règles d'alerte sont évaluées

# Indique à Prometheus où trouver les fichiers de règles d'alerte
rule_files:
  - "rules/*.yml" # Charge tous les fichiers .yml dans le sous-répertoire 'rules'
  
scrape_configs:
  - job_name: 'prometheus' # Nom du job pour Prometheus lui-même
    static_configs:
      - targets: ['localhost:9090'] # Prometheus se monitorera lui-même
  - job_name: 'news_classifier_api'
    static_configs:
      - targets: ['news-classifier-api:8080']
    