# deployment/prometheus/rules/alert_rules.yml
groups:
  - name: news-classifier-alerts
    rules:
      - alert: NewsClassifierApiDown
        expr: up{job="news_classifier_api"} == 0 # La condition PromQL qui déclenche l'alerte
        for: 1m # L'alerte se déclenche si la condition est vraie pendant 1 minute continue
        labels:
          severity: critical # Label pour la gravité de l'alerte (utile pour filtrer et prioriser)
        annotations:
          summary: "L'API de classification de nouvelles est injoignable."
          description: "Le job 'news_classifier_api' est en statut DOWN (injoignable) depuis plus de 1 minute. Veuillez vérifier le conteneur `news-classifier`."
